### ISSUE TITLE
There is an integration issue with silverstripe/html5 on dev/build

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-recipe-cms#10] opened 2018-09-14 05:00 UTC
This appears to be new, I'm unsure what has introduced it.
as a dev/build on a fresh install it is a very poor first experience :(
This has occurred with `cwp/cwp-recipe-cms` @ `2.1.0`:
```
Creating database records

CWPDemo\Model\Site
SilverStripe\Assets\File
SilverStripe\SiteConfig\SiteConfig
SilverStripe\Taxonomy\TaxonomyTerm
SilverStripe\Taxonomy\TaxonomyType
SilverStripe\Versioned\ChangeSet
SilverStripe\Versioned\ChangeSetItem
CWP\CWP\Model\Quicklink
SilverStripe\Assets\Shortcodes\FileLink
SilverStripe\CMS\Model\SiteTree
[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'getElementsByTagName' does not exist on 'SilverStripe\HTML5\HTML5Value'
GET /dev/build
Line 54 in /srv/http/core/vendor/silverstripe/framework/src/Core/CustomMethods.php

Source
45      * @throws BadMethodCallException
46      */
47     public function __call($method, $arguments)
48     {
49         // If the method cache was cleared by an an Object::add_extension() / Object::remove_extension()
50         // call, then we should rebuild it.
51         $class = static::class;
52         $config = $this->getExtraMethodConfig($method);
53         if (empty($config)) {
54             throw new BadMethodCallException(
55                 "Object->__call(): the method '$method' does not exist on '$class'"
56             );
57         }
58 
59         switch (true) {
60             case isset($config['callback']): {
Trace
SilverStripe\View\ViewableData->__call(getElementsByTagName, Array) 
HTMLValue.php:148
SilverStripe\View\Parsers\HTMLValue->__call(getElementsByTagName, Array) 
FileLinkTrackingParser.php:30
SilverStripe\Assets\Shortcodes\FileLinkTrackingParser->process(SilverStripe\HTML5\HTML5Value) 
FileLinkTracking.php:163
SilverStripe\Assets\Shortcodes\FileLinkTracking->trackLinksInField(Content, ) 
FileLinkTracking.php:124
SilverStripe\Assets\Shortcodes\FileLinkTracking->augmentSyncLinkTracking(, , , , , , ) 
Extensible.php:464
SilverStripe\View\ViewableData->extend(augmentSyncLinkTracking) 
SiteTree.php:1523
SilverStripe\CMS\Model\SiteTree->syncLinkTracking() 
FileLinkTracking.php:92
SilverStripe\Assets\Shortcodes\FileLinkTracking->onBeforeWrite(, , , , , , ) 
Extensible.php:464
SilverStripe\View\ViewableData->extend(onBeforeWrite, ) 
DataObject.php:1184
SilverStripe\ORM\DataObject->onBeforeWrite() 
SiteTree.php:1466
SilverStripe\CMS\Model\SiteTree->onBeforeWrite() 
DataObject.php:1330
SilverStripe\ORM\DataObject->preWrite() 
DataObject.php:1491
SilverStripe\ORM\DataObject->write() 
SiteTree.php:1430
SilverStripe\CMS\Model\SiteTree->requireDefaultRecords() 
DatabaseAdmin.php:386
SilverStripe\ORM\DatabaseAdmin->doBuild(, 1) 
DatabaseAdmin.php:147
SilverStripe\ORM\DatabaseAdmin->build() 
DatabaseAdmin.php:119
SilverStripe\ORM\DatabaseAdmin->index(SilverStripe\Control\HTTPRequest) 
RequestHandler.php:320
SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, index) 
Controller.php:284
SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, index) 
RequestHandler.php:202
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) 
Controller.php:212
SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) 
DevBuildController.php:32
SilverStripe\Dev\DevBuildController->build(SilverStripe\Control\HTTPRequest) 
RequestHandler.php:320
SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, build) 
Controller.php:284
SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, build) 
RequestHandler.php:202
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) 
Controller.php:212
SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) 
RequestHandler.php:226
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) 
Controller.php:212
SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) 
Director.php:361
SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
VersionedHTTPMiddleware.php:40
SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
BasicAuthMiddleware.php:68
SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
AuthenticationMiddleware.php:61
SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
CanonicalURLMiddleware.php:188
SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPCacheControlMiddleware.php:42
SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
ChangeDetectionMiddleware.php:27
SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
FlushMiddleware.php:29
SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
RequestProcessor.php:66
SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HybridSessionMiddleware.php:18
SilverStripe\HybridSessions\Control\HybridSessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
AllowedHostsMiddleware.php:60
SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
TrustedProxyMiddleware.php:176
SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
InitialisationMiddleware.php:53
CWP\Core\Control\InitialisationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) 
Director.php:370
SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:48
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure, SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:66
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure, SilverStripe\Control\HTTPRequest) 
ErrorControlChainMiddleware.php:56
SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain) 
call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain) 
ErrorControlChain.php:236
SilverStripe\Core\Startup\ErrorControlChain->step() 
ErrorControlChain.php:226
SilverStripe\Core\Startup\ErrorControlChain->execute() 
ErrorControlChainMiddleware.php:69
SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) 
HTTPApplication.php:67
SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1) 
HTTPApplication.php:49
SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) 
index.php:26
```

**Comment by robbieaverill** [comment] 2018-09-14 07:28
Related: https://github.com/silverstripe/silverstripe-html5/issues/15

I'd like to see this re-validated on CWP 2.1.1. If it's not an issue with that version then we should close it

**Comment by NightJar** [comment] 2018-09-16 23:48
Unfortunately still a thing.
![image](https://user-images.githubusercontent.com/778003/45602269-92184380-ba6f-11e8-881b-12257b4cc873.png)

**Comment by robbieaverill** [comment] 2018-09-17 07:07
Cannot reproduce:

```
composer create-project cwp/cwp-recipe-cms ./cms21dev 2.1.x-dev
cd cms21dev
# make a .env file
vendor/bin/sake dev/build flush=1
```

Can you provide any extra information to help debug this?

**Comment by NightJar** [comment] 2018-09-17 23:03
🤔 Interesting.
It doesn't seem like it would be environmental, but perhaps running `PHP 7.2` is a factor in this.

**Comment by robbieaverill** [comment] 2018-09-17 23:19
Also worth noting that Travis hasn't picked this up yet either

**Comment by robbieaverill** [comment] 2019-02-22 06:15
Feel free to reopen if you can still reproduce this!

**Closed as completed by robbieaverill** 2019-02-22 06:15 UTC
Labels: type/bug, affects/v4, feedback-required/author, impact/medium
